### ISSUE TITLE
fluid-type

### ISSUE THREAD

**Issue by dbox** [jescalan/axis#236]
So here's one I'm going to be using a lot:

Fluid-type
http://codepen.io/dbox/pen/meaMba

which I ported from [here](https://github.com/seaneking/postcss-responsive-type) which evidently was based on some stuff @corysimmons was doing (👊cory :tada: )

Let me know if you want it in @jenius and I'll convert to stylus and get it added.

It does bring up an issue, however, that if everything is going to get post-css converted then we're creating some unnecessary conversion work... but I need it now, so I'm happy to add and share.

**Comment by jenius** [comment]
This is nice!

**Comment by dbox** [comment]
http://codepen.io/dbox/pen/mVPmBo?editors=010

got stylus version going. Will get this added.
