### ISSUE TITLE
PostCSS Port

### ISSUE THREAD

**Issue by declandewet** [jescalan/axis#259]
Opening this as a place of discussion for porting to PostCSS, as this has now made an appearance on the horizon for the roadmap with all the lovely progress on [roots-mini](/carrot/roots-mini).

Things to discuss:
- Will the Stylus version still be maintained?
  - Perhaps we should offer support for other preprocessors via the PostCSS interface? (I do this in [system](/declandewet/system) by auto-generating mixin files for each preprocessor - downside of this approach is that PostCSS still has to be configured, but the end result is the same, the developer is still able to not care about PostCSS once it has been configured)
- Will Axis-PostCSS implement its own API with `@rules` or will it consume other plugins in the same way Rucksack and CSSnext combine smaller plugins?

Things to be careful of:
- Deprecated methods. Since I first published [system](/declandewet/system), the PostCSS methods for enumerating CSS nodes (selectors, properties, declarations, etc) has been depracated and replaced with other methods three times. This is less likely to happen now, but the velocity in which this occurred leads me to believe that keeping guards up will pay off in the end.

**Comment by jenius** [comment]
My thoughts:

- Stylus version will be maintained if there are bugs, but not improved. Basically just LTS mode.
- I like the mixins idea, +1 for that
- Probably the rucksack/cssnext approach

**Comment by dbox** [comment]
I definitely would like to be able to use axis via both scss and stylus. I've been living in between worlds for a while and really need ONE place to store all the goods.

**Comment by declandewet** [comment]
It's worth noting that its always possible to combine the axis-specific api with a rucksack/cssnext approach

**Comment by dbox** [comment]
@declandewet hop in gitter/axis real quick if you have second. I have some questions and dont want to clog this thread

**Comment by dbox** [comment]
**Axis Features that already exist in PostCSS:**

Axis Feature                                                   | PostCss Implementation                                                             | Notes
-------------------------------------------------------------- | ---------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------
[easings](http://axis.netlify.com/#easing)                     | [postcss-easings](https://github.com/postcss/postcss-easings)                      | May need to add a couple of the non-standard ones like `swift`, but not high priority imho.
[ratio-box](http://axis.netlify.com/#ratio-box)                | [postcss-aspect-ratio](https://github.com/arccoza/postcss-aspect-ratio)            |
[quantity queries](http://axis.netlify.com/#quantity-at-least) | [postcss-quantity-queries](https://github.com/pascalduez/postcss-quantity-queries) |
[group](http://axis.netlify.com/#group)                        | [postcss-clearfix](https://github.com/seaneking/postcss-clearfix)                  | I know @jescalan is Team `group`, but I actually really like the `clear:fix` syntax.
[absolute/fixed](http://axis.netlify.com/#absolute)            | [postcss-position](https://github.com/seaneking/postcss-position)                  |
[vertically-align](http://axis.netlify.com/#vertically-align)  | [postcss-center](https://github.com/jedmao/postcss-center)                         | This method actually can cause weird blurry pixels in rare cases (Axis does too). Obsolete with Flexfox, but still pretty handy to have I suppose.
[triangle](http://axis.netlify.com/#triangle)                  | [postcss-triangle](https://github.com/jedmao/postcss-triangle)                     |
[rem](http://axis.netlify.com/#rem)                            | [postcss-pxtorem](https://github.com/cuth/postcss-pxtorem)                         | I'm questioning value of this lately, but this does what it needs to.
[range](http://axis.netlify.com/#range)                        | [postcss-inputstyle](https://github.com/seaneking/postcss-input-style)             | untested
[fluid-type](https://github.com/jescalan/axis/issues/236) | [postcss-responsive-type](https://github.com/seaneking/postcss-responsive-type)

**Comment by dbox** [comment]
@declandewet 
Can you elaborate more on this:
> It's worth noting that its always possible to combine the axis-specific api with a rucksack/cssnext approach

Axis has a LOT of variables. How are you envisioning that they work (and still be easily accessed via other pre-processors). How much extra work are we looking at to keep the backwards compatibility?

**Comment by declandewet** [comment]
@dbox what I meant was we use existing tooling plugins, and create our own separate ones for any functionality that doesn't exist, then we combine all that into a "plugin pack" the same way CSSNext/Rucksack do it.

Anything backwards-compatible, we would have to build _on top_ of this plugin pack.

**Comment by dbox** [comment]
Yeah, okay. I think that's the only way. But I think a lot of the syntax is going to have to change regardless.
