### ISSUE TITLE
Text-and box-shadow helper and presets

### ISSUE THREAD

**Issue by FranzSkuffka** [jescalan/axis#277]
A collection of text-shadow and box-shadow presets would speed up my workflow quite a lot. What do you think? Is this possibly in the scope of axis?

**Comment by dbox** [comment]
Yeah, I think its appropriate.

I have these made (sass currently) that I use a bit, currently:
http://codepen.io/dbox/pen/JXjezq

**Comment by FranzSkuffka** [comment]
They are pretty awesome! I am going to file a pull request sometime soon.

**Comment by FranzSkuffka** [comment]
Dismissed:
https://github.com/jescalan/axis/pull/294#issuecomment-223974267
