### ISSUE TITLE
meyer-reset / normalize / sanitize

### ISSUE THREAD

**Issue by dbox** [jescalan/axis#290]
Currently Axis has includes Meyer-reset and Normalize for convenience.
1. Do we still want to do this?
2. Which do you find yourself using more?
3. Have you looked into [sanitize.css](https://github.com/10up/sanitize.css)?
4. Would this be better suited as an option in Sprout where user can just pick during setup?

**Comment by dbox** [comment]
Even if we don't use sanitize, I think we should go ahead and make all elements be `box-sizing: border-box;`

**Comment by dbox** [comment]
Here is a little thing I made so you can test the differences across all elements:

https://github.com/dbox/html5-kitchen-sink

http://codepen.io/dbox/pen/eZNBPJ

**Comment by jescalan** [comment]
Sanitize looks pretty good, I'd be ok with trying that out. Personally I used normalize more, but I know a decent number of people used the global reset in axis just from questions and filed issues that came in.

Personally I'm good with setting border box on everything, I always do that anyway. If anyone else is watching this and wants to weigh in now is the time.

The kitchen sink project is awesome, nice work on this. Definitely will be using that in the future! What's the best way to actually see the difference? Maybe we could set up the codepen to toggle between a couple options?

**Comment by dbox** [comment]
So far the best way to see the difference is just to attach external css 
![image](https://cloud.githubusercontent.com/assets/296130/15696453/048277c2-2776-11e6-8a64-22e15a417d14.png)
Then link to the CDN for sanitize, bootstrap, etc

But agreed, maybe would be cooler if that was one click toggling somehow.

**Comment by dbox** [comment]
and done:

http://codepen.io/dbox/pen/eZNBPJ

**Comment by jescalan** [comment]
Damn, this is awesome. So the only thing I notice that's different about sanitize is that it strips all the fieldset styles, otherwise it seems just slightly superior to normalize. And bootstrap's defaults are actually quite nice without all the rest of the library haha.

**Comment by dbox** [comment]
> otherwise it seems just slightly superior to normalize
From what I'm seeing, yes. Plus it has the nice border-box stuff built in. @jonathantneal is putting a lot of good work into it. I'm down to make it the default.

> And bootstrap's defaults are actually quite nice without all the rest of the library haha. 
Yeah, definitely. Bootstrap does *some* things very well. I just can't get down with their forced markup and classes. Axis default (additive mixins) will be better though. :)
