### ISSUE TITLE
1.0 Buttons

### ISSUE THREAD

**Issue by dbox** [jescalan/axis#292]
I vote we remove `glossy-button` and replace it with `outline-button` (with options)

**Comment by FranzSkuffka** [comment]
I agree on adding `outline-button` but why remove `glossy-button`?
It would break backwards-compatibility and some skeuomorphism still makes perfect sense in modern UIs.

**Comment by dbox** [comment]
I'm only talking about in `1.0.0` Postcss release which is pretty much certainly going to break stuff. But just one. (because i don't want to have to remake it :) )
