### ISSUE TITLE
Drop IE 9.0

### ISSUE THREAD

**Issue by dbox** [jescalan/axis#293]
IMHO it's time.

![ie](https://cloud.githubusercontent.com/assets/296130/15652576/c2546d62-264c-11e6-8ba1-ba04cf421fec.png)

**0.2%** of browsers, and Microsoft dropped support in Janurary. There is a bit of code still specifically for IE9 that we could strip out. And it would open the door to make some very cool new stuff as well.

Thoughts?

**Comment by dbox** [comment]
Related to #290 as sanitize is ie10+

**Comment by FranzSkuffka** [comment]
BTW I am integrating the material shadows atm & the `-ms-`-prefix is breaking the tests in the `hyphens` helper. 2 tests are failing, hyphens & additive framework.

**Comment by dbox** [comment]
This thread was also just for the new PostCSS version... (everything labeled 1.0). I'm unsure why tests are failing..

**Comment by FranzSkuffka** [comment]
Sorry.
Should I delete my comments on the 1.0.0 threads and open a new issue for the failing tests?
I think it's because the autoprefixer database was updated.

**Comment by jescalan** [comment]
I'm 👍 for dropping IE9 support
