### ISSUE TITLE
Option to remove round borders

### ISSUE THREAD

**Issue by alanaasmaa** [jescalan/axis#296]
Option to remove round borders.

**Comment by jescalan** [comment]
I'm sorry, could you add a little more detail to this issue?

**Comment by jescalan** [comment]
What do you mean by "everything"? Let's get started by listing out elements you are interested in.

**Comment by thasmog** [comment]
Buttons, fields, inputs

**Comment by jescalan** [comment]
Awesome -- ok the next step is to fork the repo and add the option, then open up a pull request with the changes 😁

**Comment by jescalan** [comment]
...or close the issue! haha

**Comment by alanaasmaa** [comment]
Im pretty new to this kind of stuff and i don't have time right now to dig into it. I will try do to this later. I closed the issue cause this is not that kind of "issue". Haha

**Comment by dbox** [comment]
**chants** 👏  ALAN! ALAN! You can do it!

**Comment by jescalan** [comment]
open source is all about teamwork! get your name on that contributor list, the glory will be worth it

**Comment by dbox** [comment]
Maybe something like this?

**settings.styl**
```sass

// Set to null to remove all rounded borders
$global-border-radius = 3px

```
**code.styl**
```sass
code($color = #DF5C33)
  padding: 3px 4px
  color: $color
  background-color: #F5F5F5
  border: 1px solid #E1E1E8
  font-family: Menlo, Monaco, $monospace
  
  if $global-border-radius
    border-radius: $global-border-radius

```

**Comment by alanaasmaa** [comment]
@dbox thanks for the tip. When i looked the code i was thinking it would be more practical to give button or input field one more option

button($color,$size,$text-color,$border-radius) then it would not be global. And maybe someone would like to make different fields look a bit different. Also global default would be creat too.

**Comment by dbox** [comment]
I'd say if you're going to pick and chose which ones get it, might as well just do it in the css code. No point in passing that many arguments for every mixin.
